# Generated by Django 4.0 on 2021-12-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=128)),
                ('lname', models.CharField(default='', max_length=128)),
                ('dptm', models.CharField(default='', max_length=128)),
                ('stream', models.CharField(default='', max_length=128)),
                ('password', models.CharField(default='', max_length=128)),
                ('cpassword', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=128)),
                ('mob_no', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
