# Generated by Django 4.0 on 2021-12-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preg_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_tb',
            name='username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
