# Generated by Django 4.0 on 2021-12-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preg_form', '0002_reg_tb_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_tb',
            name='cpassword',
        ),
    ]
